### ISSUE TITLE
Плагины

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#18]
Сейчас у тебя в проекте лежат файлы плагинов, у которых есть свои репозитории, поэтому их нужно подключить через npm. 

![Снимок экрана в 2019-10-06 20-55-33](https://user-images.githubusercontent.com/38564412/66273380-0640a780-e87c-11e9-9d82-fafafe133f40.png)

**Comment by Hahahayabanan** [comment]
Второй плагин - это расширение для jQuery ui-datepicker, добавляющее возможность выбора нескольких дат. У него только статья на хабре и гитхаб гист. Как с ним поступить?

**Comment by MorganaLF** [comment]
В таком случае вопрос почему было выбрано именно это решение?
Стоить почитать вот эти рекомендации стандартов: https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/libraries.md

**Comment by Hahahayabanan** [comment]
Стандарты были изучены на этапе рефакторинга, сильно позже, чем когда я это делал. А менять плагин - значит переделывать блок с нуля.
