### ISSUE TITLE
webpack.base.config

### ISSUE THREAD

**Issue by performanceArtist** [Hahahayabanan/FSD-2nd-task#2]
В файле как-то не очевидно сделано подключение изображений и генерация страниц. Сделана будто автоматическая генерация html-файлов(...PAGES.map), но следом за ней делается всё "вручную". Зачем используется CopyWebpackPlugin, если и так есть file-loader?

**Comment by performanceArtist** [comment]
Теперь вижу, страницы генерируются. Надо ещё сам конфиг почистить - там есть пара неиспользуемых импортов и много комментариев, которые там особо не нужны. Вместо eslint-ignore правила лучше вынести в конфиг.

Ещё почему-то в файле используются двойные кавычки, хотя в других js-файлах они одинарные. Для исправления таких мелочей можно использовать prettier, чтобы форматировать автоматически. Заодно указать правило trailing-comma, т.к. оно требуется по [стандартам](https://github.com/airbnb/javascript#commas--dangling) и добавить скрипт в package.json для автоформатирования всех файлов проекта.

**Comment by performanceArtist** [comment]
.button_faint-wrap - модификатор используется без блока. 

dropdown_furniture, dropdown__options_furniture - используется один модификатор, который надо именовать прилагательным или например with-furniture. Если нужно изменить несколько элементов, то достаточно использовать один модификатор на блоке, а внутри уже задать правила для каждого элемента. Вот пример, т.к. там не совсем очевидно по селекторам:
```
.dropdown.dropdown_furniture{
  max-width: 266px;

  & &__options {
    max-width: 266px;
    height: auto;
    padding-bottom: 8px;
  }
}
```

**Comment by Hahahayabanan** [comment]
А как поступить с этим правилом? global.$ = $ в index.js не помогает
![image](https://user-images.githubusercontent.com/43137324/65817116-7dd75c80-e214-11e9-9740-68ff461706df.png)

**Comment by performanceArtist** [comment]
У меня такого не видно, но это явно линтер - попробуй в .eslintrc добавить jquery:
```
env: {
    browser: true,
    es6: true,
    jquery: true
  },
```
