### ISSUE TITLE
Ссылки на индексной странице

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#21]
Сейчас в dev режиме на индексной странице ссылки вида: `http://localhost:8081/cards.html`, которые дают ошибку

![Снимок экрана в 2019-10-09 18-16-12](https://user-images.githubusercontent.com/38564412/66494801-e5b55f00-eac0-11e9-9a61-c634f68f95f4.png)

![Снимок экрана в 2019-10-09 18-15-23](https://user-images.githubusercontent.com/38564412/66494735-d0d8cb80-eac0-11e9-8a76-5231765b7a5d.png)

страницы открываются, например, по таким путям: `http://localhost:8081/ui-kit/cards.html`

Изображения при этом не подгружаются:

![Снимок экрана в 2019-10-09 18-13-54](https://user-images.githubusercontent.com/38564412/66494624-a555e100-eac0-11e9-982b-10bc0ab5fba1.png)

**Comment by Hahahayabanan** [comment]
Интересно, а у меня открывается, жесткую перезагрузку делал, кеш чистил
![image](https://user-images.githubusercontent.com/43137324/66495923-1b5f4580-eacb-11e9-9320-7e3821a56429.png)

**Comment by MorganaLF** [comment]
Попробуй с гитхаба скачать свой проект и запустить, нормально откроется?

**Comment by Hahahayabanan** [comment]
Да, открывается

**Comment by MorganaLF** [comment]
Твой проект глянул Вячеслав, у него так же открывается по адресу http://localhost:8081/website-pages/sign-in/sign-in.html, а твои ссылки выдают ошибку. Надо разбираться, в чем дело. 

Давай по шагам: я скачиваю проект с помощью `git clone`, запускаю с ветки master `npm run dev` и смотрю проект по адресу http://localhost:8081/ 
Есть ли что-то, что ты делаешь кроме этого?

**Comment by Hahahayabanan** [comment]
Нет, я делаю также, хотя после установки ещё сделал npm audit fix

**Comment by Hahahayabanan** [comment]
UPD: попросил друга развернуть проект у себя на пк, этими же тремя командами - у него открываются ссылки и подгружаются картинки.

**Comment by Elbereth-Gilthoniel** [comment]
> UPD: попросил друга развернуть проект у себя на пк, этими же тремя командами - у него открываются ссылки и подгружаются картинки.
Не знаю, могу ли я тут писать, учитывая, что я никто по имени никак, но у меня тоже работает после git clone, npm i, npm run dev
