### ISSUE TITLE
Элементы блоков

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#22]
Можешь объяснить, почему всё-таки решил элементы блоков выносить в отдельные папки? Сейчас довольно трудно в проекте ориентироваться, плюс об этом много раз говорилось на риззоме и в чатах.

**Comment by Hahahayabanan** [comment]
Начитался методологии, самому не очень нравится.

**Comment by MorganaLF** [comment]
> Начитался методологии, самому не очень нравится

Да, но тут еще стоит оценить преимущества/недостатки. Сейчас, например, я вижу недостаток в том, что в случае перемены имени блока нужно будет искать по всем файлам. Плюс это не наглядно и громоздко, сложная поддержка. А вот преимуществ не вижу.

По стандартам FSD мы следуем не всем рекомендациям БЭМ, например, не используем примеси по ряду причин. Здесь аналогично.
