### ISSUE TITLE
Захардкоженность

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#23]
Всё, что теоретически может поменяться, нужно спускать сверху, зашивать в компоненты стоит только то, что является частью их реализации. Вот тут, например, явно должна быть возможность поменять текст:

![Снимок экрана в 2019-10-09 19-38-01](https://user-images.githubusercontent.com/38564412/66501702-88270f80-eacc-11e9-85a5-8eb6b2d3de64.png)

Вот такие тексты тоже могут меняться

![Снимок экрана в 2019-10-09 19-40-05](https://user-images.githubusercontent.com/38564412/66501746-a4c34780-eacc-11e9-9824-93a33ca35de3.png)

Посмотри по всему проекту, где еще есть такое

**Comment by MorganaLF** [comment]
Вот здесь прямо в выпадающий список зашиты названия опций и значения, выбранные по умолчанию. 

Если понадобится вместо спален и кроватей сделать выпадающий список с чем-то другим, но при этом оставить существующий, то что делать? Или нужно будет по умолчанию поменять выбранное значение на "1 спальня, 1 кровать", а они не меняются. 

![Снимок экрана в 2019-10-13 11-17-54](https://user-images.githubusercontent.com/38564412/66712852-b1d18680-edab-11e9-8a95-cdf3cab609e8.png)

И зачем было всё дублировать в else if? Там же всё одинаковое, кроме кнопок

**Comment by MorganaLF** [comment]
Аналогично: что, если мне потребуется карточка для комнаты с другим номером и другой ценой / валютой / не в сутки, а в неделю?

![Снимок экрана в 2019-10-13 11-33-43](https://user-images.githubusercontent.com/38564412/66712992-89e32280-edad-11e9-9004-f6d363277ca8.png)

**Comment by MorganaLF** [comment]
А "люкс" остался захардкоженным. Тут надо пытаться представить, как это всё будет на практике: на практике навряд ли все комнаты будут люкс, и для каждой навряд ли будет создаваться отдельный блок. Понадобится переменная.

**Comment by Hahahayabanan** [comment]
На "люкс" была булева переменная, отображать надпись или нет. Но так и правда лучше

**Comment by MorganaLF** [comment]
В info-table в js также захардкожены параметры:

![Снимок экрана в 2019-11-04 12-21-55](https://user-images.githubusercontent.com/38564412/68110323-c5c95d80-fefd-11e9-9233-5f48054a806b.png)
