### ISSUE TITLE
Теги без классов

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#28]
По стандартам https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md

![Снимок экрана в 2019-10-13 12-49-35](https://user-images.githubusercontent.com/38564412/66713799-f6631f00-edb7-11e9-8348-a7582699d289.png)

Вот здесь например совсем непонятно, зачем столько спанов

![Снимок экрана в 2019-10-13 12-52-00](https://user-images.githubusercontent.com/38564412/66713869-4a6e0380-edb8-11e9-8080-309c73ecbcd2.png)

**Comment by Hahahayabanan** [comment]
Столько спанов нужно, чтобы построить "каркас" блока. Я отделил динамические значения от статических, чтобы их можно было легко хранить и изменять через js.
