### ISSUE TITLE
BEM

### ISSUE THREAD

**Issue by performanceArtist** [Hahahayabanan/FSD-2nd-task#3]
В основном всё написано по методологии, но в index.pug и нескольких других страницах элементы используется вне блока(к примеру, input__label, registration__back).

**Comment by performanceArtist** [comment]
В названии блока button-long присутствует прилагательное, которое смотрится как модификатор для button. Нужно либо совместить button и button-long, либо по-другому переименовать button-long. С footer-creative и masked-text-field похожая проблема - название блока должно описывать что это, а не какое оно - за это отвечает модификатор.

**Comment by performanceArtist** [comment]
.button_faint-wrap - модификатор используется без блока. 

dropdown_furniture, dropdown__options_furniture - используется один модификатор, который надо именовать прилагательным или например with-furniture. Если нужно изменить несколько элементов, то достаточно использовать один модификатор на блоке, а внутри уже задать правила для каждого элемента. Вот пример, т.к. там не совсем очевидно по селекторам:
```
.dropdown {
  &_furniture & {
    max-width: 266px;
    &__options {
        max-width: 266px;
        height: auto;
        padding-bottom: 8px;
    }
  }
}
```

**Comment by performanceArtist** [comment]
info-table__first-p, info-table__second-p - именование не очень, надо пересмотреть. Также модификатор _result - существительное - можно заменить на with-result, как в [стандартах](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md) или выбрать подходящее прилагательное. В option-button тоже есть проблемы с этим.

**Comment by performanceArtist** [comment]
В button используется элемент без блока(.button__wrap, .button__arrow). А так я думаю всё в порядке.

**Comment by Hahahayabanan** [comment]
Извиняюсь за глупый вопрос, тег "button" может выполнять роль блока?

**Comment by performanceArtist** [comment]
Может - в принципе, любой тег может, думаю. Но на него надо класс повесить, т.к. селекторы по тегам не рекомендуется делать - у них слишком широкая область действия.

**Comment by Hahahayabanan** [comment]
Спасибо, исправил

**Comment by performanceArtist** [comment]
Ок, у меня пока всё по issues. Этот проект ещё проверяющая одна посмотрит. Ну или я ещё добавлю по мелочи, если замечу. А так по-моему хорошо сделал, без сильных косяков - видно что нормально разобрался.
