### ISSUE TITLE
Фиксированная высота

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#34]
Опять встречаю жестко заданную высоту, об этом есть в стандартах, пункт 5: https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/rules.md

Надо проверить по всему проекту и поправить всё, чтобы не нужно было каждый раз открывать ишью

![Снимок экрана в 2019-10-24 19-13-26](https://user-images.githubusercontent.com/38564412/67504695-8a739700-f692-11e9-80fc-bff9d2fee597.png)

**Comment by Hahahayabanan** [comment]
![image](https://user-images.githubusercontent.com/43137324/67635167-2abcfc00-f8dd-11e9-996d-da6d0663aeee.png)
![image](https://user-images.githubusercontent.com/43137324/67635170-327ca080-f8dd-11e9-83be-b1d360fd4242.png)
![image](https://user-images.githubusercontent.com/43137324/67635173-3dcfcc00-f8dd-11e9-8651-d0c2d800cad1.png)
Правильно я понял, что таких элементов допускается фиксированная высота? Если этого не сделать окружность может деформироваться и т.д.

**Comment by MorganaLF** [comment]
Речь идет об элементах с текстовым содержимым, или о каких-то контейнерах типа твоего футера, где содержимое может поменяться и высота станет проблемой. Тут надо задаться вопросом, может ли гипотетически поменяться то, что лежит внутри? Если да, то жестко задавать высоту нельзя. А если это просто какой-то декоративный элемент, то возможно и фиксированная подойдет.

**Comment by MorganaLF** [comment]
А вот это значение почему такое странное? Я так понимаю, высота была конкретным значением задана, чтобы под перфект пиксель подогнать, но зачем там вычитание? Если 17 пикселей имеют какое-то значение, то надо их в переменную, а если нет, то надо результат вычитания сразу и записать.

![Снимок экрана в 2019-10-30 21-58-50](https://user-images.githubusercontent.com/38564412/67889950-d924a380-fb60-11e9-93b2-bfde00b2d6b1.png)
