### ISSUE TITLE
DonutChart

### ISSUE THREAD

**Issue by MorganaLF** [Hahahayabanan/FSD-2nd-task#36]
Js тут явно нуждается в рефакторинге. Как минимум, атрибуты можно передавать объектами. 

![Снимок экрана в 2019-10-30 22-55-15](https://user-images.githubusercontent.com/38564412/67893807-5a336900-fb68-11e9-85c6-568ddcf63072.png)

Ну и вообще как-то очень много однотипного кода

**Comment by Hahahayabanan** [comment]
![image](https://user-images.githubusercontent.com/43137324/67948647-98c83280-fbff-11e9-8de3-7248a2460496.png)
Вот так атрибуты передать нельзя, если имеется ввиду что-то другое - то я не понял.

**Comment by MorganaLF** [comment]
Почему нельзя? Посмотри пример в доках: https://api.jquery.com/attr/

**Comment by Hahahayabanan** [comment]
Да, но здесь используется не jquery, a d3. Не знаю стоит ли их смешивать в одном файле

**Comment by MorganaLF** [comment]
Есть тогда вот такая штука: https://github.com/d3/d3-selection-multi
Сейчас от обилия attr рябит в глазах))
